name: Reusable deploy
on:
  workflow_call:
    inputs:
      artifact:
        description: "Artifact to deploy"
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
      - name: Output info
        run: echo "Deploying & uploading..."
